{{- if .Values.externalSecrets.enabled }}
{{- if eq .Values.externalSecrets.provider "gcp-secret-manager" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "opencrane.fullname" . }}-gcp-secret-manager
  labels:
    {{- include "opencrane.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ required "tenant.storage.gcpProject is required for gcp-secret-manager" .Values.tenant.storage.gcpProject }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.tenant.storage.gcpProject }}
          clusterName: ""
          serviceAccountRef:
            name: {{ include "opencrane.fullname" . }}-external-secrets
            namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
