#!/usr/bin/env bash
# =============================================================================
# OpenCrane Platform — GCP Bootstrap Script
#
# Interactive script that sets up gcloud, builds + pushes Docker images,
# runs Prisma migrations, and deploys the full platform via Terraform.
#
# Usage:
#   ./deploy.sh
#
# Prerequisites:
#   - gcloud CLI installed
#   - terraform >= 1.5 installed
#   - docker installed and running
#   - pnpm installed (for local Prisma migration generation)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()   { echo -e "${GREEN}[opencrane]${NC} $1"; }
warn()  { echo -e "${YELLOW}[opencrane]${NC} $1"; }
err()   { echo -e "${RED}[opencrane]${NC} $1" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$SCRIPT_DIR/terraform"

# ---- Pre-flight checks ----

for cmd in gcloud terraform docker pnpm; do
  if ! command -v "$cmd" &>/dev/null; then
    err "Required command not found: $cmd"
    exit 1
  fi
done

# ---- Interactive prompts ----

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║     OpenCrane Platform — GCP Deploy      ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

read -rp "GCP Project ID: " PROJECT_ID
read -rp "GCP Region [europe-west1]: " REGION
REGION="${REGION:-europe-west1}"
read -rp "Base domain (e.g. opencrane.example.com): " DOMAIN
read -rp "Environment [dev]: " ENVIRONMENT
ENVIRONMENT="${ENVIRONMENT:-dev}"

IMAGE_TAG="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo 'latest')"
VPC_NAME="opencrane-${ENVIRONMENT}-vpc"
CLUSTER_NAME="opencrane-${ENVIRONMENT}-cluster"

echo ""
log "Configuration:"
echo "  Project:       $PROJECT_ID"
echo "  Region:        $REGION"
echo "  Domain:        $DOMAIN"
echo "  Environment:   $ENVIRONMENT"
echo "  GKE mode:      Autopilot (auto-managed nodes)"
echo "  Image tag:     $IMAGE_TAG"
echo ""
read -rp "Proceed? [Y/n]: " CONFIRM
CONFIRM="${CONFIRM:-Y}"
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
  echo "Aborted."
  exit 0
fi

# ---- Step 1: Configure gcloud ----

log "Step 1/7 — Configuring gcloud..."

gcloud config set project "$PROJECT_ID"
gcloud config set compute/region "$REGION"

# Enable required APIs
APIS=(
  container.googleapis.com
  compute.googleapis.com
  artifactregistry.googleapis.com
  dns.googleapis.com
  iam.googleapis.com
  cloudresourcemanager.googleapis.com
)

log "Enabling GCP APIs..."
gcloud services enable "${APIS[@]}" --quiet

# ---- Step 2: Terraform init ----

log "Step 2/7 — Initialising Terraform..."
cd "$TF_DIR"
terraform init -upgrade

# ---- Step 3: Write tfvars ----

log "Step 3/7 — Writing terraform.tfvars..."

ENV_DIR="$TF_DIR/environments/${ENVIRONMENT}"
mkdir -p "$ENV_DIR"

cat > "$ENV_DIR/terraform.tfvars" <<EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

project_id  = "${PROJECT_ID}"
region      = "${REGION}"
environment = "${ENVIRONMENT}"
domain      = "${DOMAIN}"
image_tag   = "${IMAGE_TAG}"

# Networking
vpc_name = "${VPC_NAME}"

# GKE (Autopilot — Google manages nodes)
cluster_name = "${CLUSTER_NAME}"
EOF

log "Wrote $ENV_DIR/terraform.tfvars"

# ---- Step 4: Terraform apply (infra only — networking + GKE + registry) ----

log "Step 4/7 — Provisioning cloud infrastructure (VPC, GKE, Artifact Registry)..."
terraform apply \
  -var-file="environments/${ENVIRONMENT}/terraform.tfvars" \
  -target=module.networking \
  -target=module.gke \
  -target=module.artifact_registry \
  -auto-approve

# ---- Step 5: Build & push Docker images ----

log "Step 5/7 — Building and pushing Docker images..."

REGISTRY_URL=$(terraform output -raw registry_url)

# Authenticate Docker with Artifact Registry
gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet

# Get GKE credentials for kubectl
gcloud container clusters get-credentials "$CLUSTER_NAME" \
  --region "$REGION" \
  --project "$PROJECT_ID"

cd "$REPO_ROOT"

# Generate Prisma migration files before building images
log "Generating Prisma migration..."
cd apps/control-plane
pnpm install --frozen-lockfile 2>/dev/null || pnpm install
npx prisma generate
npx prisma migrate dev --name init --create-only 2>/dev/null || true
cd "$REPO_ROOT"

# Build control-plane (includes UI)
log "Building control-plane image..."
docker build \
  -f apps/control-plane/deploy/Dockerfile \
  -t "${REGISTRY_URL}/control-plane:${IMAGE_TAG}" \
  -t "${REGISTRY_URL}/control-plane:latest" \
  .

docker push "${REGISTRY_URL}/control-plane:${IMAGE_TAG}"
docker push "${REGISTRY_URL}/control-plane:latest"

# Build operator
log "Building operator image..."
docker build \
  -f apps/operator/deploy/Dockerfile \
  -t "${REGISTRY_URL}/operator:${IMAGE_TAG}" \
  -t "${REGISTRY_URL}/operator:latest" \
  .

docker push "${REGISTRY_URL}/operator:${IMAGE_TAG}"
docker push "${REGISTRY_URL}/operator:latest"

# ---- Step 6: Terraform apply (full — Crossplane + App + DNS) ----

log "Step 6/7 — Deploying platform (Crossplane, PostgreSQL, OpenCrane, DNS)..."
cd "$TF_DIR"
terraform apply \
  -var-file="environments/${ENVIRONMENT}/terraform.tfvars" \
  -auto-approve

# ---- Step 7: Output summary ----

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║             OpenCrane Platform — Deployed!           ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

INGRESS_IP=$(terraform output -raw ingress_ip)
CONTROL_PLANE_URL=$(terraform output -raw control_plane_url)
DNS_NS=$(terraform output -json dns_name_servers)

log "Ingress IP:           $INGRESS_IP"
log "Control-plane URL:    $CONTROL_PLANE_URL"
log "Registry:             $REGISTRY_URL"
echo ""
warn "ACTION REQUIRED — Delegate your domain's NS records:"
echo "  Domain: $DOMAIN"
echo "  Name servers:"
echo "$DNS_NS" | tr -d '[]"' | tr ',' '\n' | sed 's/^ */    /'
echo ""
log "Once DNS propagates, your platform is live at: $CONTROL_PLANE_URL"
log "Create tenants via: kubectl apply -f <tenant-cr.yaml>"
echo ""
