apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencrane.fullname" . }}-control-plane
  labels:
    {{- include "opencrane.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opencrane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
