{{- if .Values.crossplane.enabled }}
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ include "opencrane.fullname" . }}-gcp
  labels:
    {{- include "opencrane.labels" . | nindent 4 }}
spec:
  projectID: {{ required "tenant.storage.gcpProject is required when crossplane is enabled" .Values.tenant.storage.gcpProject }}
  credentials:
    source: InjectedIdentity
{{- end }}
