{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "opencrane.fullname" . }}-org-secrets
  labels:
    {{- include "opencrane.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    {{- if eq .Values.externalSecrets.provider "gcp-secret-manager" }}
    name: {{ include "opencrane.fullname" . }}-gcp-secret-manager
    {{- else }}
    name: {{ include "opencrane.fullname" . }}-secret-store
    {{- end }}
  target:
    name: {{ .Values.orgSecrets.secretName }}
    creationPolicy: Owner
  {{- if .Values.orgSecrets.envMappings }}
  data:
    {{- range $secretKey, $envVar := .Values.orgSecrets.envMappings }}
    - secretKey: {{ $envVar }}
      remoteRef:
        key: {{ $secretKey }}
    {{- end }}
  {{- end }}
{{- end }}
