apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencrane.fullname" . }}-operator
  labels:
    {{- include "opencrane.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "opencrane.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        {{- include "opencrane.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: {{ include "opencrane.fullname" . }}-operator
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.operator.watchNamespace | quote }}
            - name: TENANT_DEFAULT_IMAGE
              value: "{{ .Values.tenant.defaultImage.repository }}:{{ .Values.tenant.defaultImage.tag }}"
            - name: INGRESS_DOMAIN
              value: {{ .Values.ingress.domain | quote }}
            - name: INGRESS_CLASS_NAME
              value: {{ .Values.ingress.className | quote }}
            - name: STORAGE_PROVIDER
              value: {{ .Values.tenant.storage.provider | quote }}
            - name: BUCKET_PREFIX
              value: {{ .Values.tenant.storage.bucketPrefix | quote }}
            - name: GCP_PROJECT
              value: {{ .Values.tenant.storage.gcpProject | quote }}
            - name: CSI_DRIVER
              value: {{ .Values.tenant.storage.csiDriver | quote }}
            - name: CROSSPLANE_ENABLED
              value: {{ .Values.crossplane.enabled | quote }}
            - name: IDLE_TIMEOUT_MINUTES
              value: {{ .Values.operator.idleTimeoutMinutes | quote }}
            - name: IDLE_CHECK_INTERVAL_SECONDS
              value: {{ .Values.operator.idleCheckIntervalSeconds | quote }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
